### PR TITLE
#163037245 Write tests for getting a specific question.

### PR DESCRIPTION
**Pull request by cod3smith**
#### What does this PR do?
This PR contains the tests for the `Get specific question record` endpoint. 

#### Description of Task to be completed?
- [x] Create tests for the `Get specific question records` endpoint.

#### How should this be manually tested?
To manually test this:
1. Clone the repository using:
`git clone https://github.com/KelynPNjeri/Questioner-API.git`
2. Through your terminal, navigate to the cloned repository on your local machine and open it.
3. While in the folder on your terminal, change branches to the ` ch-test-get-question-163037245` using `git checkout  ch-test-get-question-163037245`.
4. From your terminal, navigate into the `app` folder then into the `tests` folder then into the `v1` folder.
5. Open the `test_question.py` file.
6. Run your tests with pytest.

#### Any background context you want to provide?
This is the backend of the Questioner Web App.

#### What are the relevant pivotal tracker stories?
[#163037245](https://www.pivotaltracker.com/story/show/163037245)

### CODE REVIEW

**Comment by Bakley** [comment]
Good job on the test

**Comment by KelynPNjeri** [comment]
> Good job on the test

Thanks @Bakl

> Good job on the test

Thanks @Bakley

**Comment by SolomonMacharia** [comment]
Nice

**Comment by cod3smith** [comment]
Thanks @Bakley  and @ SolomonMacharia

**Pull request merged**
